passing the solver as a part of the constructor  in `CCMLogicSolver`
CogComp/Logic2ILP pull request #5
Opened 2016-09-27 04:36 UTC by danyaljj

Minor change: 
 - Passing the `ILPProblem` to the constructor of `CCMLogicSolver`.

2016-09-28 16:25 UTC, haowu40 requested changes

2016-09-28 16:25 UTC, haowu4 commented on core/src/main/java/edu/illinois/cs/cogcomp/l2ilp/inference/CCMLogicSolver.java
> +        prepare(problem);
Change the order of 49 and 50.
Otherwise prepare will access this.maximizeObjective, which is undefined at this point.

2016-09-28 16:29 UTC, haowu4 commented
BTW, I'm thinking about your comment on ILPSolver vs ILPProblem.
Ideally, we should merge the two. But I can imagine it is hard to do because the way LBJava is handling ILP.

How about we move ILPProblem to illinois-inference, and put a deprecated annotation for ILPSolver class. And point people to use ILPProblem instead manage the bookkeeping on their own.

Also I don't like the name ILPSolver, I think a more appropriate should be ILPProblem.

2016-09-28 17:01 UTC, danyaljj commented on core/src/main/java/edu/illinois/cs/cogcomp/l2ilp/inference/CCMLogicSolver.java
> +        prepare(problem);
Good catch! Fixed.

2016-10-01 20:31 UTC, haowu40 approved these changes
LGTM.

2016-10-01 20:31 UTC, haowu40 commented on core/src/main/java/edu/illinois/cs/cogcomp/l2ilp/inference/CCMLogicSolver.java
> +    private void prepare(ILPProblem problem) {
Also change the signature to prepare()

2016-10-01 20:32 UTC, merged